package testejb.bean.impl;

import testejb.EOrder;
import testejb.bean.OrderBean;

import javax.ejb.Remote;
import javax.ejb.Stateless;



@Stateless
@Remote(OrderBean.class)
public class OrderBeanImpl implements OrderBean {


    @Override
    public String getMessage() {
        return "Message generated by ejb component";
    }

    @Override
    public int addOrder(EOrder eOrder) {

        System.out.println(eOrder.getOrderNumber());

        return 0;
    }
}
